spring.application.name=ss-dam

# Server Port
server.port=9090


# mariaDB 
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/ssdam
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=ssdam
spring.datasource.password=ssdam


