spring.application.name=ss-dam

# Server Port
server.port=9090

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url: jdbc:mariadb://172.16.144.51:3306/team2
spring.datasource.username: team2
spring.datasource.password: 1234

mybatis.type-aliases-package: com.ss_dam.*
mybatis.mapper-locations: classpath:mapper/**/*.xml

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB