spring.application.name=ss-dam

# Server Port
server.port=9090

<<<<<<< HEAD
=======
# mariaDB 
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/ssdam
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=ssdam
spring.datasource.password=ssdam
>>>>>>> 92f31fe92cc8326f1c3cf7cfc6ce9ba86f42e104
